package dbx

import (
	"fmt"
	"sort"
	"strings"
)

// ORM schema generation is this dashboard's answer to "does it support Prisma".
// The honest support a server panel can give is introspection: read the live
// database and emit the schema file a developer would otherwise get from
// `prisma db pull` or `drizzle-kit pull`, without needing either CLI or a
// Node toolchain on the box. The output is a reviewed starting point, not a
// guaranteed drop-in — Postgres keeps no canonical DDL, type mappings are
// lossy in both directions, and relation names are inferred — so every
// generated file says so in its header.
//
// These functions are pure: they take an introspected structure and return
// text, which is what lets them be unit-tested without a database.

// ORMTarget names a supported code generator.
type ORMTarget string

const (
	ORMPrisma  ORMTarget = "prisma"
	ORMDrizzle ORMTarget = "drizzle"
)

func (t ORMTarget) Valid() bool {
	switch t {
	case ORMPrisma, ORMDrizzle, ORMTypeScript, ORMZod:
		return true
	}
	return false
}

// ORMTargets is the list the UI offers, kept here so a new generator appears in
// the picker without a second list to update.
func ORMTargets() []ORMTarget {
	return []ORMTarget{ORMPrisma, ORMDrizzle, ORMTypeScript, ORMZod}
}

// GenerateORM dispatches to the requested generator. Mongo is rejected here
// rather than producing a misleading relational schema.
func GenerateORM(target ORMTarget, driver Driver, tables []Table, details map[string]*TableDetail) (string, error) {
	if driver == DriverMongo {
		return "", fmt.Errorf("ORM schema generation covers the SQL engines; use the connection's native tooling for MongoDB")
	}
	switch target {
	case ORMPrisma:
		return GeneratePrismaSchema(driver, tables, details), nil
	case ORMDrizzle:
		return GenerateDrizzleSchema(driver, tables, details), nil
	case ORMTypeScript:
		return GenerateTypeScript(tables, details), nil
	case ORMZod:
		return GenerateZod(tables, details), nil
	default:
		return "", fmt.Errorf("unsupported ORM target %q", target)
	}
}

// prismaProvider maps our driver identity onto Prisma's datasource provider.
func prismaProvider(driver Driver) string {
	switch driver {
	case DriverMySQL:
		return "mysql"
	case DriverSQLite:
		return "sqlite"
	default:
		return "postgresql"
	}
}

// prismaType maps a SQL column type onto a Prisma scalar. The match is on the
// leading word of the type so that "varchar(255)" and "numeric(10,2)" resolve
// like their bare forms.
func prismaType(sqlType string) string {
	switch baseType(sqlType) {
	case "bool", "boolean", "bit":
		return "Boolean"
	case "smallint", "int2", "integer", "int", "int4", "mediumint", "serial", "smallserial", "year":
		return "Int"
	case "bigint", "int8", "bigserial":
		return "BigInt"
	case "real", "double", "float", "float4", "float8", "double precision":
		return "Float"
	case "numeric", "decimal", "money", "dec":
		return "Decimal"
	case "date", "time", "timestamp", "timestamptz", "datetime", "timestamp with time zone", "timestamp without time zone":
		return "DateTime"
	case "json", "jsonb":
		return "Json"
	case "bytea", "blob", "binary", "varbinary", "longblob", "mediumblob", "tinyblob":
		return "Bytes"
	default:
		return "String"
	}
}

// baseType lowercases a column type and strips any length/precision suffix and
// array/unsigned decorations, leaving the leading type word.
func baseType(sqlType string) string {
	t := strings.ToLower(strings.TrimSpace(sqlType))
	t = strings.TrimSuffix(t, "[]")
	if i := strings.IndexByte(t, '('); i >= 0 {
		t = t[:i]
	}
	t = strings.TrimSpace(t)
	for _, suffix := range []string{" unsigned", " zerofill"} {
		t = strings.TrimSuffix(t, suffix)
	}
	// Keep multi-word type names that the maps above expect intact, otherwise
	// reduce to the first word.
	switch t {
	case "double precision", "timestamp with time zone", "timestamp without time zone",
		"character varying", "timestamp with", "timestamp without":
		return t
	}
	if i := strings.IndexByte(t, ' '); i >= 0 {
		return t[:i]
	}
	return t
}

func GeneratePrismaSchema(driver Driver, tables []Table, details map[string]*TableDetail) string {
	var b strings.Builder
	b.WriteString("// Generated by Just Dashboard from live database introspection.\n")
	b.WriteString("// A reviewed starting point: verify types, defaults and relation\n")
	b.WriteString("// names before committing. Set DATABASE_URL in your environment.\n\n")
	b.WriteString("datasource db {\n")
	fmt.Fprintf(&b, "  provider = %q\n", prismaProvider(driver))
	b.WriteString("  url      = env(\"DATABASE_URL\")\n}\n\n")
	b.WriteString("generator client {\n  provider = \"prisma-client-js\"\n}\n")

	// Back-relations are collected as the forward relations are emitted, then
	// appended to each parent model: Prisma requires both ends of a relation.
	backrefs := map[string][]string{}
	type modelBlock struct {
		name string
		text string
	}

	models := make([]Table, 0, len(tables))
	for _, t := range tables {
		if strings.EqualFold(t.Type, "view") {
			continue
		}
		models = append(models, t)
	}

	blocks := make([]modelBlock, 0, len(models))
	for _, t := range models {
		d := details[t.Name]
		if d == nil {
			continue
		}
		var mb strings.Builder
		pk := map[string]bool{}
		for _, c := range d.PrimaryKey {
			pk[c] = true
		}
		uniqueSingle, _ := uniqueSets(d)

		fmt.Fprintf(&mb, "\nmodel %s {\n", prismaModelName(t.Name))
		for _, c := range d.Columns {
			field := prismaFieldName(c.Name)
			typ := prismaType(c.Type)
			if c.Nullable {
				typ += "?"
			}
			line := fmt.Sprintf("  %s %s", field, typ)
			if len(d.PrimaryKey) == 1 && pk[c.Name] {
				line += " @id"
			}
			if uniqueSingle[c.Name] {
				line += " @unique"
			}
			if field != c.Name {
				line += fmt.Sprintf(" @map(%q)", c.Name)
			}
			mb.WriteString(line + "\n")
		}
		// Forward relations, one per foreign key.
		for _, fk := range d.ForeignKeys {
			if fk.RefTable == "" || len(fk.Columns) == 0 {
				continue
			}
			relName := prismaRelationName(t.Name, fk)
			fwd := relationFieldName(fk)
			refModel := prismaModelName(fk.RefTable)
			localFields := mapFields(fk.Columns, prismaFieldName)
			refFields := mapFields(fk.RefColumns, prismaFieldName)
			optional := ""
			if fkNullable(d, fk) {
				optional = "?"
			}
			fmt.Fprintf(&mb, "  %s %s%s @relation(%q, fields: [%s], references: [%s])\n",
				fwd, refModel, optional, relName,
				strings.Join(localFields, ", "), strings.Join(refFields, ", "))
			back := fmt.Sprintf("  %s %s[] @relation(%q)",
				pluralFieldName(t.Name), prismaModelName(t.Name), relName)
			backrefs[fk.RefTable] = append(backrefs[fk.RefTable], back)
		}
		blocks = append(blocks, modelBlock{name: t.Name, text: mb.String()})
	}

	for _, blk := range blocks {
		b.WriteString(blk.text)
		for _, back := range backrefs[blk.name] {
			b.WriteString(back + "\n")
		}
		// Composite primary key and multi-column unique constraints.
		d := details[blk.name]
		if d != nil {
			if len(d.PrimaryKey) > 1 {
				fmt.Fprintf(&b, "\n  @@id([%s])\n", strings.Join(mapFields(d.PrimaryKey, prismaFieldName), ", "))
			}
			for _, cols := range uniqueMultiOf(d) {
				fmt.Fprintf(&b, "  @@unique([%s])\n", strings.Join(mapFields(cols, prismaFieldName), ", "))
			}
			if prismaModelName(blk.name) != blk.name {
				fmt.Fprintf(&b, "  @@map(%q)\n", blk.name)
			}
		}
		b.WriteString("}\n")
	}
	return b.String()
}

// uniqueSets splits a table's unique indexes (excluding the primary key) into
// single-column ones (rendered inline as @unique) and multi-column ones.
func uniqueSets(d *TableDetail) (single map[string]bool, multi [][]string) {
	single = map[string]bool{}
	for _, ix := range d.Indexes {
		if !ix.Unique || ix.Primary || len(ix.Columns) == 0 {
			continue
		}
		if len(ix.Columns) == 1 {
			single[ix.Columns[0]] = true
		} else {
			multi = append(multi, ix.Columns)
		}
	}
	return single, multi
}

func uniqueMultiOf(d *TableDetail) [][]string {
	_, multi := uniqueSets(d)
	return multi
}

func fkNullable(d *TableDetail, fk ForeignKey) bool {
	null := map[string]bool{}
	for _, c := range d.Columns {
		null[c.Name] = c.Nullable
	}
	for _, c := range fk.Columns {
		if !null[c] {
			return false
		}
	}
	return true
}

func mapFields(cols []string, f func(string) string) []string {
	out := make([]string, len(cols))
	for i, c := range cols {
		out[i] = f(c)
	}
	return out
}

// prismaModelName leaves the table name as the model identity when it is a legal
// Prisma model name, so a matching @@map is only added when the two differ.
func prismaModelName(table string) string {
	return sanitizeIdent(table)
}

func prismaFieldName(col string) string { return sanitizeIdent(col) }

// sanitizeIdent replaces characters Prisma forbids in an identifier ($, leading
// digit) so the generated schema parses; the original name is preserved through
// an @map/@@map at the call site when it differs.
func sanitizeIdent(name string) string {
	var b strings.Builder
	for i, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r == '_':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			if i == 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	s := b.String()
	if s == "" {
		return "field"
	}
	return s
}

func relationFieldName(fk ForeignKey) string {
	// user_id -> user, author_id -> author; falls back to the referenced table.
	if len(fk.Columns) == 1 {
		base := strings.TrimSuffix(strings.ToLower(fk.Columns[0]), "_id")
		base = strings.TrimSuffix(base, "id")
		if base != "" && base != fk.Columns[0] {
			return sanitizeIdent(camelLower(base))
		}
	}
	return sanitizeIdent(camelLower(fk.RefTable))
}

func pluralFieldName(table string) string {
	n := camelLower(table)
	if strings.HasSuffix(n, "s") {
		return n
	}
	return n + "s"
}

func prismaRelationName(childTable string, fk ForeignKey) string {
	return childTable + "_" + strings.Join(fk.Columns, "_")
}

func camelLower(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// --- Drizzle -------------------------------------------------------------

// drizzleImport is the column-builder module for the driver.
func drizzleImport(driver Driver) (module, table string) {
	switch driver {
	case DriverMySQL:
		return "drizzle-orm/mysql-core", "mysqlTable"
	case DriverSQLite:
		return "drizzle-orm/sqlite-core", "sqliteTable"
	default:
		return "drizzle-orm/pg-core", "pgTable"
	}
}

// drizzleColumn renders a column builder call for the driver and SQL type.
func drizzleColumn(driver Driver, name, sqlType string) string {
	q := fmt.Sprintf("%q", name)
	base := baseType(sqlType)
	if driver == DriverSQLite {
		switch prismaType(sqlType) {
		case "Int", "BigInt", "Boolean", "DateTime":
			return fmt.Sprintf("integer(%s)", q)
		case "Float", "Decimal":
			return fmt.Sprintf("real(%s)", q)
		case "Bytes":
			return fmt.Sprintf("blob(%s)", q)
		default:
			return fmt.Sprintf("text(%s)", q)
		}
	}
	if driver == DriverMySQL {
		switch base {
		case "int", "integer", "int4", "mediumint", "smallint", "int2", "tinyint", "year":
			return fmt.Sprintf("int(%s)", q)
		case "bigint", "int8":
			return fmt.Sprintf("bigint(%s, { mode: \"number\" })", q)
		case "bool", "boolean":
			return fmt.Sprintf("boolean(%s)", q)
		case "numeric", "decimal", "dec":
			return fmt.Sprintf("decimal(%s)", q)
		case "float", "double", "real":
			return fmt.Sprintf("double(%s)", q)
		case "date":
			return fmt.Sprintf("date(%s)", q)
		case "datetime", "timestamp":
			return fmt.Sprintf("timestamp(%s)", q)
		case "json":
			return fmt.Sprintf("json(%s)", q)
		case "text", "longtext", "mediumtext", "tinytext":
			return fmt.Sprintf("text(%s)", q)
		default:
			return fmt.Sprintf("varchar(%s, { length: 255 })", q)
		}
	}
	// Postgres
	switch base {
	case "int", "integer", "int4", "smallint", "int2", "serial", "smallserial":
		return fmt.Sprintf("integer(%s)", q)
	case "bigint", "int8", "bigserial":
		return fmt.Sprintf("bigint(%s, { mode: \"number\" })", q)
	case "bool", "boolean":
		return fmt.Sprintf("boolean(%s)", q)
	case "numeric", "decimal":
		return fmt.Sprintf("numeric(%s)", q)
	case "real", "float4":
		return fmt.Sprintf("real(%s)", q)
	case "double", "float8", "double precision":
		return fmt.Sprintf("doublePrecision(%s)", q)
	case "date":
		return fmt.Sprintf("date(%s)", q)
	case "timestamp", "timestamptz", "timestamp with time zone", "timestamp without time zone":
		return fmt.Sprintf("timestamp(%s)", q)
	case "json":
		return fmt.Sprintf("json(%s)", q)
	case "jsonb":
		return fmt.Sprintf("jsonb(%s)", q)
	case "uuid":
		return fmt.Sprintf("uuid(%s)", q)
	case "bytea":
		return fmt.Sprintf("bytea(%s)", q)
	case "text":
		return fmt.Sprintf("text(%s)", q)
	default:
		return fmt.Sprintf("varchar(%s, { length: 255 })", q)
	}
}

func GenerateDrizzleSchema(driver Driver, tables []Table, details map[string]*TableDetail) string {
	module, tableFn := drizzleImport(driver)
	// Collect the builder names actually used so the import line is honest.
	used := map[string]bool{tableFn: true}

	var body strings.Builder
	for _, t := range tables {
		if strings.EqualFold(t.Type, "view") {
			continue
		}
		d := details[t.Name]
		if d == nil {
			continue
		}
		pk := map[string]bool{}
		for _, c := range d.PrimaryKey {
			pk[c] = true
		}
		single, _ := uniqueSets(d)
		fmt.Fprintf(&body, "export const %s = %s(%q, {\n", drizzleVar(t.Name), tableFn, t.Name)
		for _, c := range d.Columns {
			call := drizzleColumn(driver, c.Name, c.Type)
			used[callName(call)] = true
			line := fmt.Sprintf("  %s: %s", drizzleVar(c.Name), call)
			if len(d.PrimaryKey) == 1 && pk[c.Name] {
				line += ".primaryKey()"
			}
			if !c.Nullable {
				line += ".notNull()"
			}
			if single[c.Name] {
				line += ".unique()"
			}
			body.WriteString(line + ",\n")
		}
		body.WriteString("})\n\n")
	}

	names := make([]string, 0, len(used))
	for n := range used {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Generated by Just Dashboard from live database introspection.\n")
	b.WriteString("// A reviewed starting point: verify types and add relations as needed.\n\n")
	fmt.Fprintf(&b, "import { %s } from %q\n\n", strings.Join(names, ", "), module)
	b.WriteString(strings.TrimRight(body.String(), "\n"))
	b.WriteString("\n")
	return b.String()
}

// callName extracts the builder function name from a rendered call like
// `varchar("x", …)` so it can be added to the import list.
func callName(call string) string {
	if i := strings.IndexByte(call, '('); i >= 0 {
		return call[:i]
	}
	return call
}

// drizzleVar renders a name as a legal JS identifier for use as a variable or
// object key; Drizzle keeps the real column name in the builder's first
// argument, so any sanitising here is cosmetic.
func drizzleVar(name string) string {
	s := sanitizeIdent(name)
	return s
}

// --- TypeScript and Zod ---------------------------------------------------
//
// Prisma and Drizzle are what you generate when the ORM owns the schema. A web
// developer reading rows out of an existing database and shaping them into an
// API response wants neither: they want the row's type, and something that
// validates a payload before it becomes one. Those are the two files below.

const (
	ORMTypeScript ORMTarget = "typescript"
	ORMZod        ORMTarget = "zod"
)

// tsType maps a SQL column onto a TypeScript type.
//
// bigint becomes string, not number: a 64-bit integer does not survive
// JSON.parse intact, and silently rounding an id is the kind of bug that
// surfaces months later as two records mysteriously becoming one.
func tsType(sqlType string) string {
	switch prismaType(sqlType) {
	case "Boolean":
		return "boolean"
	case "Int", "Float":
		return "number"
	case "BigInt", "Decimal":
		return "string"
	case "DateTime":
		return "string"
	case "Json":
		return "unknown"
	case "Bytes":
		return "string"
	default:
		return "string"
	}
}

func zodType(sqlType string) string {
	switch prismaType(sqlType) {
	case "Boolean":
		return "z.boolean()"
	case "Int":
		return "z.number().int()"
	case "Float":
		return "z.number()"
	case "BigInt", "Decimal":
		return "z.string()"
	case "DateTime":
		// Coerced rather than z.string(): a date arrives as a string over JSON
		// and as a Date from a driver, and a schema that only accepts one of
		// those fails on whichever half of the app it did not anticipate.
		return "z.coerce.date()"
	case "Json":
		return "z.unknown()"
	default:
		return "z.string()"
	}
}

// pascal renders a table name as a type name: user_profiles -> UserProfiles.
func pascal(name string) string {
	parts := strings.FieldsFunc(sanitizeIdent(name), func(r rune) bool { return r == '_' })
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	if b.Len() == 0 {
		return "Row"
	}
	return b.String()
}

// singular is a deliberately shallow de-pluraliser. A table called `users`
// should produce a `User`, and getting that right for the common cases is worth
// more than an inflection library; anything it gets wrong is one rename away
// and the generated file is meant to be read before it is used.
func singular(name string) string {
	switch {
	case strings.HasSuffix(name, "ies") && len(name) > 3:
		return name[:len(name)-3] + "y"
	case strings.HasSuffix(name, "sses"), strings.HasSuffix(name, "shes"), strings.HasSuffix(name, "ches"):
		return name[:len(name)-2]
	case strings.HasSuffix(name, "s") && !strings.HasSuffix(name, "ss"):
		return name[:len(name)-1]
	}
	return name
}

func GenerateTypeScript(tables []Table, details map[string]*TableDetail) string {
	var b strings.Builder
	b.WriteString("// Generated by Just Dashboard from live database introspection.\n")
	b.WriteString("// Row types as the database returns them. A nullable column is `| null`\n")
	b.WriteString("// rather than optional: the key is always present, its value may not be.\n")
	for _, t := range tables {
		d := details[t.Name]
		if d == nil || len(d.Columns) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\nexport interface %s {\n", pascal(singular(t.Name)))
		for _, c := range d.Columns {
			typ := tsType(c.Type)
			if c.Nullable {
				typ += " | null"
			}
			fmt.Fprintf(&b, "  %s: %s\n", tsPropertyName(c.Name), typ)
		}
		b.WriteString("}\n")
	}
	return b.String()
}

// tsPropertyName quotes a key that is not a bare JS identifier, rather than
// renaming it: the key has to match what the database actually returns.
func tsPropertyName(name string) string {
	if name == "" {
		return `""`
	}
	for i, r := range name {
		ok := r == '_' || r == '$' ||
			(r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(i > 0 && r >= '0' && r <= '9')
		if !ok {
			return fmt.Sprintf("%q", name)
		}
	}
	return name
}

func GenerateZod(tables []Table, details map[string]*TableDetail) string {
	var b strings.Builder
	b.WriteString("// Generated by Just Dashboard from live database introspection.\n")
	b.WriteString("// One schema per table, plus an `Insert` variant with the columns the\n")
	b.WriteString("// database fills in made optional — which is the difference between a\n")
	b.WriteString("// schema you can validate a row with and one you can validate a form with.\n\n")
	b.WriteString(`import { z } from "zod"` + "\n")

	for _, t := range tables {
		d := details[t.Name]
		if d == nil || len(d.Columns) == 0 {
			continue
		}
		name := pascal(singular(t.Name))
		fmt.Fprintf(&b, "\nexport const %sSchema = z.object({\n", name)
		for _, c := range d.Columns {
			expr := zodType(c.Type)
			if c.Nullable {
				expr += ".nullable()"
			}
			fmt.Fprintf(&b, "  %s: %s,\n", tsPropertyName(c.Name), expr)
		}
		b.WriteString("})\n")
		fmt.Fprintf(&b, "export type %s = z.infer<typeof %sSchema>\n", name, name)

		// The insert variant: anything with a default, or a single-column
		// primary key the database generates, is optional on the way in.
		pk := map[string]bool{}
		for _, c := range d.PrimaryKey {
			pk[c] = true
		}
		optional := []string{}
		for _, c := range d.Columns {
			if c.Default != "" || (len(d.PrimaryKey) == 1 && pk[c.Name]) {
				optional = append(optional, fmt.Sprintf("%q", c.Name))
			}
		}
		if len(optional) > 0 {
			fmt.Fprintf(&b, "export const %sInsertSchema = %sSchema.partial({ %s })\n",
				name, name, strings.Join(optional, ": true, ")+": true")
		} else {
			fmt.Fprintf(&b, "export const %sInsertSchema = %sSchema\n", name, name)
		}
	}
	return b.String()
}
